
import './globals.css'
import { Roboto } from 'next/font/google'
import NavBar from './components/Navbar'
import Footer from './components/Footer'
import Provider from '../SessionProvider'

const robotoFont = Roboto({ subsets: ['latin'] , weight: '400'})

export const metadata = {
  title: 'My workouts',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={robotoFont.className}>
          <NavBar />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
