
import Provider from './utils/SessionProvider'

import './globals.css'
import { Roboto } from 'next/font/google'

const robotoFont = Roboto({ subsets: ['latin'] , weight: '400'})

export const metadata = {
  title: 'My workouts',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoFont.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
